
#Generic functions of RedeR

#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
setGeneric ('ping',               signature='obj', function (obj)                 
            standardGeneric ('ping'),          package='RedeR')
setGeneric ('version',            signature='obj', function (obj)                 
            standardGeneric ('version'),       package='RedeR')
setGeneric ('calld',              signature='obj', function (obj,...)            
            standardGeneric ('calld'),         package='RedeR')
setGeneric ('updateGraph',        signature='obj', function (obj)                 
            standardGeneric ('updateGraph'),   package='RedeR')
setGeneric ('dynwin',             signature='obj', function (obj, ...)            
            standardGeneric ('dynwin'),        package='RedeR')
setGeneric ('getGraph',           signature='obj', function (obj, ...)            
            standardGeneric ('getGraph'),      package='RedeR')   
setGeneric ('addGraph',           signature='obj', function (obj, g, ...)            
            standardGeneric ('addGraph'),      package='RedeR')          
setGeneric ('addSeries',  	      signature='obj', function (obj, g, ...)            
            standardGeneric ('addSeries'),     package='RedeR') 
setGeneric ('duplicateGraph',     signature='obj', function (obj, ...)            
            standardGeneric ('duplicateGraph'), package='RedeR')
setGeneric ('addSubgraph',        signature='obj', function (obj, g, nodes, ...)            
            standardGeneric ('addSubgraph'),    package='RedeR')  
setGeneric ('addSubgraph.list',   signature='obj', function (obj, g, nodeList, ...)            
            standardGeneric ('addSubgraph.list'), package='RedeR')   
setGeneric ('exitd',            signature='obj', function (obj)                 
            standardGeneric ('exitd'),         package='RedeR') 
setGeneric ('resetd',           signature='obj', function (obj)                 
            standardGeneric ('resetd'),        package='RedeR') 
setGeneric ('addLegend.color',   signature='obj', function (obj, colvec, ...)            
            standardGeneric ('addLegend.color'), package='RedeR')
setGeneric ('addLegend.size',   signature='obj', function (obj, sizevec, ...)            
            standardGeneric ('addLegend.size'), package='RedeR')            
setGeneric ('addLegend.shape',   signature='obj', function (obj, shapevec, ...)            
            standardGeneric ('addLegend.shape'), package='RedeR')                                                                                            
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
setGeneric ('getNodes',           signature='obj', function (obj, ...) 
            standardGeneric ('getNodes'),          package='RedeR')
setGeneric ('getNodeIDs',         signature='obj', function (obj, ...) 
            standardGeneric ('getNodeIDs'),        package='RedeR')
setGeneric ('getNodeAliases',     signature='obj', function (obj, ...) 
            standardGeneric ('getNodeAliases'),    package='RedeR')
setGeneric ('getNodeX',           signature='obj', function (obj, ...) 
            standardGeneric ('getNodeX'),          package='RedeR')
setGeneric ('getNodeY',           signature='obj', function (obj, ...) 
            standardGeneric ('getNodeY'),          package='RedeR')
setGeneric ('getNodeW',           signature='obj', function (obj, ...) 
            standardGeneric ('getNodeW'),          package='RedeR')
setGeneric ('getNodeH',           signature='obj', function (obj, ...) 
            standardGeneric ('getNodeH'),          package='RedeR')
setGeneric ('getNodeBend',        signature='obj', function (obj, ...) 
            standardGeneric ('getNodeBend'),       package='RedeR')
setGeneric ('getNodeSize',        signature='obj', function (obj, ...) 
            standardGeneric ('getNodeSize'),       package='RedeR')
setGeneric ('getNodeShape',       signature='obj', function (obj, ...) 
            standardGeneric ('getNodeShape'),      package='RedeR')
setGeneric ('getNodeColor',       signature='obj', function (obj, ...) 
            standardGeneric ('getNodeColor'),      package='RedeR')
setGeneric ('getNodeLineWidth',   signature='obj', function (obj, ...) 
            standardGeneric ('getNodeLineWidth'),  package='RedeR')
setGeneric ('getNodeLineColor',   signature='obj', function (obj, ...) 
            standardGeneric ('getNodeLineColor'),  package='RedeR')
setGeneric ('getNodeFontName',    signature='obj', function (obj, ...) 
            standardGeneric ('getNodeFontName'),   package='RedeR')
setGeneric ('getNodeFontStyle',   signature='obj', function (obj, ...) 
            standardGeneric ('getNodeFontStyle'),  package='RedeR')
setGeneric ('getNodeFontSize',    signature='obj', function (obj, ...) 
            standardGeneric ('getNodeFontSize'),   package='RedeR')
setGeneric ('getNodeFontColor',   signature='obj', function (obj, ...) 
            standardGeneric ('getNodeFontColor'),  package='RedeR')
setGeneric ('getNodeFontX',       signature='obj', function (obj, ...) 
            standardGeneric ('getNodeFontX'),      package='RedeR')
setGeneric ('getNodeFontY',       signature='obj', function (obj, ...) 
            standardGeneric ('getNodeFontY'),      package='RedeR')
setGeneric ('getNodeWeight',      signature='obj', function (obj, ...) 
            standardGeneric ('getNodeWeight'),     package='RedeR')
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
setGeneric ('setNodeAlias',    signature='obj', function (obj, node, alias) 
            standardGeneric ('setNodeAlias'),  package='RedeR')
setGeneric ('setNodeXY',          signature='obj', function (obj, node, x, y)   
            standardGeneric ('setNodeXY'),        package='RedeR')
setGeneric ('setNodeBend',        signature='obj', function (obj, node, bend)   
            standardGeneric ('setNodeBend'),      package='RedeR')
setGeneric ('setNodeSize',        signature='obj', function (obj, node, size)   
            standardGeneric ('setNodeSize'),      package='RedeR')
setGeneric ('setNodeShape',       signature='obj', function (obj, node, shape)  
            standardGeneric ('setNodeShape'),     package='RedeR')
setGeneric ('setNodeColor',       signature='obj', function (obj, node, color)  
            standardGeneric ('setNodeColor'),     package='RedeR')
setGeneric ('setNodeLineWidth',   signature='obj', function (obj, node, width)  
            standardGeneric ('setNodeLineWidth'), package='RedeR') 
setGeneric ('setNodeLineColor',   signature='obj', function (obj, node, color)  
            standardGeneric ('setNodeLineColor'), package='RedeR')
setGeneric ('setNodeFontName',    signature='obj', function (obj, node, name)   
            standardGeneric ('setNodeFontName'),  package='RedeR')
setGeneric ('setNodeFontStyle',   signature='obj', function (obj, node, style)  
            standardGeneric ('setNodeFontStyle'), package='RedeR')
setGeneric ('setNodeFontSize',    signature='obj', function (obj, node, size)   
            standardGeneric ('setNodeFontSize'),  package='RedeR')
setGeneric ('setNodeFontColor',   signature='obj', function (obj, node, color)  
            standardGeneric ('setNodeFontColor'), package='RedeR')
setGeneric ('setNodeFontXY',      signature='obj', function (obj, node, x, y)   
            standardGeneric ('setNodeFontXY'),    package='RedeR')
setGeneric ('setNodeWeight',      signature='obj', function (obj, node, weight) 
            standardGeneric ('setNodeWeight'),    package='RedeR')
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
setGeneric ('addNodes',           signature='obj', function (obj, nodes)      
            standardGeneric ('addNodes'),     package='RedeR')
setGeneric ('deleteNodes',        signature='obj', function (obj, nodes)      
            standardGeneric ('deleteNodes'),  package='RedeR')
setGeneric ('nestNodes',          signature='obj', function (obj, nodes,...)      
            standardGeneric ('nestNodes'),    package='RedeR')
setGeneric ('nesthc',          signature='obj', function (obj, hc,...)      
            standardGeneric ('nesthc'),    package='RedeR')            
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
setGeneric ('updateContainerSize',    signature='obj', function (obj)             
            standardGeneric ('updateContainerSize'),    package='RedeR')
setGeneric ('mergeOutEdges', signature='obj', function (obj,...)             
            standardGeneric ('mergeOutEdges'), package='RedeR')
setGeneric ('getContainerComponets',  signature='obj', function (obj, container)  
            standardGeneric ('getContainerComponets'),  package='RedeR')
setGeneric ('mergeNodes',             signature='obj', function (obj, nodes)      
            standardGeneric ('mergeNodes'),             package='RedeR')
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
setGeneric ('getEdges',           signature='obj', function (obj,...) 
            standardGeneric ('getEdges'),       package='RedeR')
setGeneric ('getSourceEdges',     signature='obj', function (obj,...) 
            standardGeneric ('getSourceEdges'), package='RedeR')
setGeneric ('getTargetEdges',     signature='obj', function (obj,...) 
            standardGeneric ('getTargetEdges'), package='RedeR')
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
setGeneric ('getEdgeIDs',         signature='obj', function (obj,...) 
            standardGeneric ('getEdgeIDs'),       package='RedeR')
setGeneric ('getSourceEdgeIDs',   signature='obj', function (obj,...) 
            standardGeneric ('getSourceEdgeIDs'), package='RedeR')
setGeneric ('getTargetEdgeIDs',   signature='obj', function (obj,...) 
            standardGeneric ('getTargetEdgeIDs'), package='RedeR')
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
setGeneric ('getArrowDirection',  signature='obj', function (obj,...) 
            standardGeneric ('getArrowDirection'), package='RedeR')
setGeneric ('getEdgeWidth',       signature='obj', function (obj,...) 
            standardGeneric ('getEdgeWidth'), package='RedeR')
setGeneric ('getEdgeColor',       signature='obj', function (obj,...) 
            standardGeneric ('getEdgeColor'), package='RedeR')
setGeneric ('getEdgeType',        signature='obj', function (obj,...) 
            standardGeneric ('getEdgeType'), package='RedeR')
setGeneric ('getEdgeWeight',      signature='obj', function (obj,...) 
            standardGeneric ('getEdgeWeight'), package='RedeR')
#-----------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------
setGeneric ('setArrowDirection',  signature='obj', function (obj, nodeA, nodeB, direction)    
            standardGeneric ('setArrowDirection'), package='RedeR')
setGeneric ('setEdgeWidth',       signature='obj', function (obj, nodeA, nodeB, width)        
            standardGeneric ('setEdgeWidth'),      package='RedeR')       
setGeneric ('setEdgeColor',       signature='obj', function (obj, nodeA, nodeB, color)        
            standardGeneric ('setEdgeColor'),      package='RedeR')
setGeneric ('setEdgeType',        signature='obj', function (obj, nodeA, nodeB, type)         
            standardGeneric ('setEdgeType'),       package='RedeR')
setGeneric ('setEdgeWeight',      signature='obj', function (obj, nodeA, nodeB, weight)       
            standardGeneric ('setEdgeWeight'),     package='RedeR')
#-----------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------
setGeneric ('addEdges',                 signature='obj', function (obj,edges)                      
            standardGeneric ('addEdges'),                 package='RedeR')
setGeneric ('deleteEdges',              signature='obj', function (obj,edges)                      
            standardGeneric ('deleteEdges'),              package='RedeR')
setGeneric ('addEdgeBetweenContainers', signature='obj', function (obj,containerA,containerB)  
            standardGeneric ('addEdgeBetweenContainers'), package='RedeR')
#-----------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------
setGeneric ('selectEdges',        signature='obj', function (obj, nodeA, nodeB)    
            standardGeneric ('selectEdges'), package='RedeR')
setGeneric ('selectNodes',        signature='obj', function (obj, nodes, nt=NULL)           
            standardGeneric ('selectNodes'), package='RedeR')
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
setGeneric ('selectAllEdges',     signature='obj', function (obj)     
            standardGeneric ('selectAllEdges'), package='RedeR')
setGeneric ('selectAllNodes',     signature='obj', function (obj)     
            standardGeneric ('selectAllNodes'), package='RedeR')
setGeneric ('selectGraph',        signature='obj', function (obj)     
            standardGeneric ('selectGraph'),    package='RedeR')
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
setGeneric ('deSelectEdges',      signature='obj', function (obj)     
            standardGeneric ('deSelectEdges'), package='RedeR')
setGeneric ('deSelectNodes',      signature='obj', function (obj)     
            standardGeneric ('deSelectNodes'), package='RedeR')
setGeneric ('deSelectGraph',      signature='obj', function (obj)     
            standardGeneric ('deSelectGraph'), package='RedeR')
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
setGeneric ('deleteSelectedEdges',  signature='obj', function (obj)   
            standardGeneric ('deleteSelectedEdges'), package='RedeR')
setGeneric ('deleteSelectedNodes',  signature='obj', function (obj)   
            standardGeneric ('deleteSelectedNodes'), package='RedeR')
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
setGeneric ('isDynamicsActive',     signature='obj', function (obj)   
            standardGeneric ('isDynamicsActive'), package='RedeR')
setGeneric ('relax',     signature='obj', 
function (obj,p1=100,p2=100,p3=100,p4=100, p5=100,p6=100,p7=10,p8=10,ps=FALSE)
            standardGeneric ('relax'), package='RedeR') 
            
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
setGeneric ('submitPlugin', signature='obj', function (obj, plugin)     
            standardGeneric ('submitPlugin'),   package='RedeR')                                                                                                                 
setGeneric ('deletePlugin', signature='obj', function (obj, pluginName) 
            standardGeneric ('deletePlugin'),   package='RedeR')
setGeneric ('updatePlugins',signature='obj', function (obj)             
            standardGeneric ('updatePlugins'),  package='RedeR')

                   
